export const GET_WEATHER_FOR_CITIES = 'weather/GET_WEATHER_FOR_CITIES';
export const GET_WEATHER_FOR_CITIES_RECEIVED = 'weather/GET_WEATHER_FOR_CITIES_RECEIVED';
export const GET_WEATHER_FOR_CITIES_FAILED = 'weather/GET_WEATHER_FOR_CITIES_FAILED';
